version: "3.8"

services:
  backend:
    build: ./backend
    container_name: ai-transcriber-backend
    ports:
      - "5066:5066"
    volumes:
      - backend_data:/app/data
    environment:
      - PORT=5066
      - UPLOAD_FOLDER=/app/data/uploads
      - TRANSCRIPT_FOLDER=/app/data/transcriptions
    restart: always

  # frontend:
  #   build: ./frontend
  #   container_name: ai-transcriber-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:5066
  #   restart: always

volumes:
  backend_data:
