version: "3.8"

services:
  backend:
    build: ./backend
    container_name: ai-transcriber-backend
    ports:
      - "5066:5066"
    volumes:
      - backend_data:/app/data
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - UPLOAD_FOLDER=/app/data/uploads
      - TRANSCRIPT_FOLDER=/app/data/transcriptions
      - SQLITE_PATH=/app/data/db
      # Postgres Verbindungsdaten
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET="alskhjgb9832z5823bn28fhgns90shv892bt89n2q9gbn298n09"
    depends_on:
      - postgres
    restart: always

  frontend:
    build: ./frontend
    container_name: ai-transcriber-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5066
    restart: always

  postgres:
    image: postgres:15
    container_name: ai-transcriber-postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

volumes: 
  backend_data:
  postgres_data:
